version: '3'
services:
  redis:
    image: redis:5
    container_name: redis-wieex-app
    command: redis-server --appendonly yes
    volumes:
      - /mydata/redis-wieex-app/data:/data #数据文件挂载
    ports:
      - 6379:6379
  wieex-app:
    image: wieex-app/wieex-app:1.0.0-SNAPSHOT
    container_name: wieex-app
    links:
      - redis:redis
    depends_on:
      - redis
    ports:
      - 8080:8080
    environment:
      - 'spring.profiles.active=prod'
      - 'spring.datasource.url=jdbc:mysql://192.168.3.105:3306/wieex_app?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false'
      - 'spring.redis.host=redis'
    volumes:
      - /etc/localtime:/etc/localtime
      - /mydata/app/wieex-app/logs:/var/logs